### ISSUE TITLE
uploaded files can be accessed by the general public

### ISSUE THREAD

**Issue by baermathias** [djpogo/strapi-node-upload#8]
Did you know, that all your uploaded files can be accessed by the general public? The file url localhost:1337/uploads/yoursong.mp3 is accessable anytime to non authenticated users.

**Comment by djpogo** [comment]
Hi @baermathias - yes I know that.

During the upload process a hash is added to the filename by strapi.
For example: `yoursong.mp3` is stored as `yoursong_00949cb280.mp3`. When you delete that file and reupload it, it gets a new hash value - so it is not a 1-on-1 mapping, yet still public accessible.

I will add your input to the blog post and the readme, to be more clear about that topic - and I will think about a protected upload handling.

thx for your input!
